name: Employment Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
    with:
      docker login -u nadhirotullaily -p dckr_pat_cH5enKfitiwCIOFpsYtz1hU7aE0
      
    - name: Build and push employment app
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./Dockerfile
        tags: docker push nadhirotullaily/employment
              
        
