name: Employment Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
    with:
      username: $ {{ secrets.DOCKER_nadhirotullaily}}
      password: $ {{ secrets.DOCKER_Laily_12}}
          
    - name: Build and push employment app
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_nadhirotullaily }}/employment:latest
