name: Apitodo Pipeline
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Scripts
        run:
          docker build -t app .
          docker login u ${{ secrets.DOCKER_USERNAME }} p ${{ secrets.DOCKER_PASSWORD }}
          docker tag app nadhirotullaily/apitodo
          docker push nadhirotullaily/apitodo
